### ISSUE TITLE
git-module does not work with the new gitdir-format submodules

### ISSUE THREAD

**Issue by ianhinder** [barrywardell/git-module#10]
In git 1.7.8 (https://lkml.org/lkml/2011/12/2/316) the submodule git directory was moved into the super-repository one.  Something in git-module or git-svn doesn't like this.

[ian@Ians-MacBook-Pro AEI (master)]$ git module init-upstream arrangements/AEIThorns/SystemStatistics
modules =  ['arrangements/AEIThorns/SystemStatistics']
modules_relpath:  ['arrangements/AEIThorns/SystemStatistics']
Initialising submodule svn upstream repository for arrangements/AEIThorns/SystemStatistics
with upstream URL https://svn.aei.mpg.de/numrel/AEIThorns/SystemStatistics
Already on 'trunk'
warning: unable to access '/Users/ian/Cactus/AEI/arrangements/AEIThorns/SystemStatistics/.git/config': Not a directory
warning: unable to access '/Users/ian/Cactus/AEI/arrangements/AEIThorns/SystemStatistics/.git/config': Not a directory
/Users/ian/Cactus/AEI/arrangements/AEIThorns/SystemStatistics/.git/refs: Not a directory
init: command returned error: 1

Traceback (most recent call last):
  File "/Users/ian/Cactus/EinsteinToolkit/bin/git-module", line 371, in <module>
    sys.exit(main(*sys.argv))
  File "/Users/ian/Cactus/EinsteinToolkit/bin/git-module", line 366, in main
    args.func(args)
  File "/Users/ian/Cactus/EinsteinToolkit/bin/git-module", line 119, in init_upstream
    map(sr.upstream_init, modules)
  File "/Users/ian/Cactus/EinsteinToolkit/repos/git-module/GitSuperRepository.py", line 165, in upstream_init
    self.git_command(['svn', 'init', '-s', '--prefix=origin/', url], module=path)
  File "/Users/ian/Cactus/EinsteinToolkit/repos/git-module/GitSuperRepository.py", line 89, in git_command
    return check_output(['git', git_dir, work_tree] + command, cwd=module_abspath).rstrip('\n')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 544, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', '--git-dir=/Users/ian/Cactus/AEI/arrangements/AEIThorns/SystemStatistics/.git', '--work-tree=/Users/ian/Cactus/AEI/arrangements/AEIThorns/SystemStatistics', 'svn', 'init', '-s', '--prefix=origin/', 'https://svn.aei.mpg.de/numrel/AEIThorns/SystemStatistics']' returned non-zero exit status 1

**Comment by barrywardell** [comment]
This is a bug in git-svn. There is a discussion and patch at http://thread.gmane.org/gmane.comp.version-control.git/192127 and http://thread.gmane.org/gmane.comp.version-control.git/192133.

**Comment by ianhinder** [comment]
A workaround is to undo the change to the repository structure by moving the .git directory from the super-repository to the submodule.  You can do this for an entire super-repository like this:

  find . -name .git -type f| while read f; do mv $f $f.bak; mv .git/modules/${f%/.git} $f; done

This is not the most robust solution (it should read the .git files rather than assuming the location in .git/modules) but it worked for me.

**Comment by ianhinder** [comment]
Almost.  You also need to modify the config files to remove the reference to the worktree:

  find . -path "*/.git/config"|while read c; do sed -i bak 's/worktree/#worktree/' $c; done

**Comment by barrywardell** [comment]
The original problem has now been fixed in https://github.com/git/git/commit/bc93ceb7c5ec959ad275f575a3c49ff491337a8b so it should be fixed in the next git release.
