### ISSUE TITLE
Use a different URL for pulling and pushing

### ISSUE THREAD

**Issue by ianhinder** [barrywardell/git-module#8]
git-module init-upstream should run

```
git remote set-url --push origin <r/w url>
```

to add an authenticated URL which is only used for pushing.  Even better would be if we could have this happen automatically by configuring something in the server version of the repository.

This works with git version 1.6.4 and later (http://stackoverflow.com/questions/2916845/diferent-default-remote-for-git-pull-and-git-push).

**Comment by barrywardell** [comment]
Commited as 0276824a6bc0a3fe9778ede2a385d45b25d9f60d.
